[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project]
name = "ty-command"
version = "2.0.0"
authors = [
    { name = "Ryan Moore", email = "ryanm.inbox@gmail.com" },
]
description = "A configurable type-checking Python command"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "mypy",
    "pyright; platform_system != 'Windows'",
    "pytype; platform_system != 'Windows'",
    "tomli",
]

[project.urls]
Homepage = "https://github.com/yrom1/ty"
"Bug Tracker" = "https://github.com/yrom1/ty/issues"

[project.scripts]
ty = "ty_command.ty:main"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[tool.ty]
type_checker = "mypy"

[tool.mypy]
pretty = true
strict = true
