[tool.poetry]
name = "csrspy"
version = "v0.4.0"
description = "ITRF/NAD83CSRS coordinate transforms in Python"
authors = ["Taylor Denouden <taylordenouden@gmail.com>"]
packages = [
    { include = "csrspy" }
]
[tool.poetry.dependencies]
python = "^3.8"
pyproj = "^3.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
tox = "^3.27.1"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
