[tool.poetry]
name = "s3-client-lib"
version = "0.2.2"
description = "S3 client lib"
authors = ["Radim Spigel <spigel@cesnet.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
boto3 = "^1.14.18"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12", "boto3"]
build-backend = "poetry.masonry.api"
