[tool.poetry]
name = "e-nowshop-models"
version = "0.4.10"
description = ""
authors = ["Your Name <you@example.com>"]

packages = [{ include = "enowshop_models" }]


[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = "^1.4.39"
psycopg2-binary = "^2.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
