[tool.poetry]
name = "tisaneCodeGenerator"
version = "0.1.0"
description = "Code generator for Tisane"
authors = ["Eunice Jun <eunice.m.jun@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"

[tool.pytest.ini_options]
pythonpath=[
    "."
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
