[tool.poetry]
name = "schemarin"
version = "0.0.0"
description = "A color scheme manager for iTerm2"
authors = ["celsius narhwal <hello@celsiusnarhwal.dev>"]

[tool.poetry.dependencies]
python = "^3.10"
inquirerpy = "^0.3.4"
click = "^8.1.3"
inflect = "^6.0.2"
colorama = "^0.4.6"
halo = "^0.0.31"
pygithub = "^1.57"
pygit2 = "^1.11.1"
validators = "^0.20.0"
loctocat = "^1.0.2"
pyperclip = "^1.8.2"
path = "^16.5.0"
toml = "^0.10.2"
colour = "^0.1.5"

[tool.poetry.group.dev.dependencies]
ptpython = "^3.0.20"
ipython = "^8.6.0"

[tool.poetry.scripts]
schemarin = "schemarin.schemarin:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
