[tool.poetry]
name = "spring-data-python"
version = "0.1.6"
description = "Spring Data Python is an offshoot of the Java-based Spring Data Framework, targeted for Python."
authors = ["Vincent TERESE <vincent.terese@gmail.com>"]
readme = "README.md"
repository = "https://github.com/kobibleu/spring-data-python"
packages = [{include = "springdata"}]

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.dev-dependencies]
black = "^22.0"
pytest = ">=7.0,<8"
pytest-mock = ">=3.0,<4"
pytest-asyncio = ">=0.19,<1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
