[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "typeguards"
description = "Utilities to help with type checking."
readme = "README.rst"
requires-python = ">=3.10"
license = {file = "LICENSE"}
keywords = ["type checker", "type checking", "type utility", "typeguard"]
authors = [
    {name = "Narvin Singh", email = "Narvin.A.Singh@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = []

[project.optional-dependencies]
code_quality = [
  "black >= 22.10.0",
  "mypy >= 0.991",
  "pycodestyle >= 2.9.1",
  "pylint >= 2.15.5",
]
docs = [
  "sphinx >= 5.3.0",
  "sphinx-rtd-theme >= 1.1.1",
]
test = [
  "pytest >= 7.2.0",
  "pytest-xdist >= 2.5.0",
]
deploy = [
  "build >= 0.7.0",
  "twine >= 4.0.0",
]

[project.urls]
Homepage = "https://gitlab.com/narvin/typeguards"
Documentation = "https://typeguards.readthedocs.io/en/stable/"
Repository = "https://gitlab.com/narvin/typeguards"
"Bug Tracker" = "https://gitlab.com/narvin/typeguards/-/issues"

[tool.setuptools]
package-data = {"*" = ["py.typed"]}

[tool.setuptools.dynamic]
version = {attr = "typeguards.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pylint.messages_control]
disable = []

[tool.mypy]
strict = true

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py3{10,11}

[testenv]
deps =
    pytest
    pytest-xdist
commands = pytest -n auto test
"""
