[tool.poetry]
name = "okadminfinder"
version = "0.1.7"
description = "[ Admin panel finder / Admin Login Page Finder ] Â¢Ïƒâˆ‚Ñ”âˆ‚ Ğ²Ñƒ ğŸ‘» (â¤-â¤) ğŸ‘»"
authors = ["mIcHyAmRaNe <marseillaisanonymous@gmail.com>"]
license = "LICENSE"
readme = "README.md"
repository = "https://github.com/mIcHyAmRaNe/okadminfinder"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Information Technology",
    "Natural Language :: English"
]

[okadminfinder.scripts]
okadminfinder = "okadminfinder.okadminfinder:main"

[tool.poetry.dependencies]
python = "^3.11"
httpx = {extras = ["socks"], version = "^0.23.1"}
colorama = "^0.4.6"
tqdm = "^4.64.1"
trio = "^0.22.0"

[tool.poetry.dev-dependencies]

# [build-system]
# requires = ["poetry-core>=1.0.0"]
# build-backend = "poetry.core.masonry.api"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
