[build-system]
requires = ["py-build-cmake~=0.1.1", "pybind11~=2.10", "pybind11-stubgen", "mypy"]
build-backend = "py_build_cmake.build"

[project]
name = "qpalm"
readme = "README.md"
requires-python = ">=3.7"
license = { "file" = "LICENSE" }
authors = [{ "name" = "Ben Hermans" }]
maintainers = [{ "name" = "Pieter Pas", "email" = "pieter.p.dev@outlook.com" }]
keywords = [
    "optimization",
    "augmented-lagrangian",
    "proximal",
    "qp",
    "quadratic-programming",
    "nonconvex",
    "ladel",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: C",
    "Programming Language :: C++",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Typing :: Typed",
]
dependencies = ["numpy~=1.19", "scipy~=1.6"]
dynamic = ["version", "description"]

[project.optional-dependencies]
debug = [
    "qpalm-debug==1.1.3"
]

[project.urls]
Source = "https://github.com/kul-optec/QPALM"
Documentation = "https://kul-optec.github.io/QPALM"
Tracker = "https://github.com/kul-optec/QPALM/issues"

[tool.py-build-cmake.module]
directory = "QPALM/interfaces/python"

[tool.py-build-cmake.sdist]
include = ["CMakeLists.txt", "LADEL", "QPALM"]

[tool.py-build-cmake.cmake]
minimum_version = "3.20"
source_path = "QPALM"
args = ["-Wdev"]
build_args = ["-j"]
install_args = []
install_components = ["python_modules", "python_stubs"]

[tool.py-build-cmake.cmake.options]
"QPALM_WITH_CXX:BOOL" = "On"
"QPALM_WITH_PYTHON:BOOL" = "On"
"QPALM_WITH_PY_STUBS:BOOL" = "On"
"CMAKE_POSITION_INDEPENDENT_CODE:BOOL" = "On"

[tool.py-build-cmake.linux.cmake]
config = ["Debug", "Release"]
generator = "Ninja Multi-Config"
[tool.py-build-cmake.mac.cmake]
config = ["Debug", "Release"]
generator = "Ninja Multi-Config"
[tool.py-build-cmake.windows.cmake]
config = ["Release"]

[tool.py-build-cmake.stubgen]
packages = []
files = ["qpalm/__init__.py"]
args = ["-v", "--no-import"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["QPALM/interfaces/python/test"]

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin"]

[tool.pyright]
# Pyright stops looking after the first match, which is usually in the 
# site-packages folder. When doing an editable install, it should look in both
# site-packages and the source folder. To get the search order correct, 
# explicitly point it to the source folder first (it will still look for the C++ 
# extension module stubs in site-packages).
extraPaths = ["QPALM/interfaces/python"]