[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rokit_vai_package"
version = "0.0.0.12"
authors = [
    { name="SangMin Lee", email="snack@rokit.co.kr" },
]
description = "rokithealthcare vertex ai tutorial pipeline package"
requires-python = ">=3.7"
classifiers = [
   "Programming Language :: Python :: 3",
   "Operating System :: OS Independent",
]
dependencies = ["opencv-python"]