[build-system]
requires = ["setuptools>=43.0.0", "wheel", "setuptools_scm[toml]>=3.4.1"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "acquire/version.py"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_first_party = ["acquire"]
